### ISSUE TITLE
Unable to import Line, Bar

### ISSUE THREAD

**Issue by LP-Codes** [reactchartjs/react-chartjs-2#636] opened 2021-04-06 11:21 UTC
Hello I am unable to to use it getting below error kindly suggest the fix 

``ypeError: Cannot read property 'defaults' of undefined
(anonymous function)
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/node_modules/react-chartjs-2/es/index.js:643
  640 | }(_react["default"].Component);
  641 | 
  642 | exports.Scatter = Scatter;
> 643 | var defaults = _chart["default"].defaults;
  644 | exports.defaults = defaults;
View compiled
./node_modules/react-chartjs-2/es/index.js
http://localhost:3000/My-First-React-App/static/js/vendors~main.chunk.js:49502:30
__webpack_require__
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module.<anonymous>
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:918:73
Module../src/Components/Charts/Charts.jsx
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:1046:30
__webpack_require__
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module.<anonymous>
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:1181:72
Module../src/Components/Covid.jsx
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:1304:30
__webpack_require__
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module.<anonymous>
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:316:64
Module../src/Components/App.jsx
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:611:30
__webpack_require__
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module.<anonymous>
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:3033:73
Module../src/index.js
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:3145:30
__webpack_require__
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
fn
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:3268:18
__webpack_require__
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:856
  853 | 
  854 | __webpack_require__.$Refresh$.init();
  855 | try {
> 856 | 	modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  857 | } finally {
  858 | 	__webpack_require__.$Refresh$.cleanup(moduleId);
  859 | }
View compiled
checkDeferredModules
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
D:/My Webapps/Web_Apps/My First React App/lp-first-react-deploy/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/My-First-React-App/static/js/main.chunk.js:1:95
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the '

**Comment by lobaak** [comment] 2021-04-06 22:53
Duplicate of #634. Try installing the latest 2.x version of chart.js

**Comment by dylanosaur** [comment] 2021-04-18 15:30
had this same problem, resolved using the above suggestion. These steps working with npm:

npm uninstall chart.js
npm install chart,js@2.9.0

**Closed** 2021-04-21 15:54 UTC
