### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by acceh** [reactchartjs/react-chartjs-2#735] opened 2021-09-21 10:02 UTC
I am getting the following errors:

`TypeError: Cannot read properties of undefined (reading 'visible')`

where the error references the following line and function:

```  
_getSortedDatasetMetas(filterVisible) {
     const me = this;
     const metasets = me._sortedMetasets;
     const result = [];
     let i, ilen;
     for (i = 0, ilen = metasets.length; i < ilen; ++i) {
       const meta = metasets[i];
       if (!filterVisible || meta.visible) { <---- THIS LINE
         result.push(meta);
       }
     }
     return result;
    }
```

`TypeError: Cannot read properties of undefined (reading 'controller')`

where the error references the following line:

`const style = meta.controller.getStyle(usePointStyle ? 0 : undefined);`

The problem is that it happens randomly and I can not find any culprit for the problem.

**Comment by ashishk14** [comment] 2021-09-21 12:10
@acceh Downgrading to version [3.0.4](https://www.npmjs.com/package/react-chartjs-2/v/3.0.4) helped me.

**Comment by dylandepass** [comment] 2021-09-28 15:07
Also ran into this issue on 3.0.5

**Comment by dangreen** [comment] 2021-11-01 09:22
Closed due to inactivity.

**Comment by honzahruby** [comment] 2021-11-02 13:35
Anyone with the same issue? Downgrade from 3.1.0 to 3.0.4 helped, looks like 3.2.0+ is fine too

**Comment by chrmcg** [comment] 2021-11-04 00:07
This is happening for me on `react-chartjs-2@3.3.0` with `chart.js@3.6.0`.

It seems that when the `data` prop passed into `<Line>` changes, this can happen and has something to do with missing `metasets` in [Chart.js/src/core/core.controller.js:_getSortedDatasetMetas](https://github.com/chartjs/Chart.js/blob/15785fdc54c5e06c1d2275dbd515c92d624b4613/src/core/core.controller.js#L713):

![image](https://user-images.githubusercontent.com/3424518/140234544-78649c08-316c-4b8d-8222-74fc0e0fa73c.png)
(note the `empty ⨉ 4` marker)

I was able to mitigate by passing `redraw={true}`:
```<Line data={data} options={options} redraw />```

But this means I lose out on the cool animation between old data and new data.

@dangreen This is a total guess, but could it be possible that the performance optimizations around [here](https://github.com/reactchartjs/react-chartjs-2/commit/330fb1cf0913bdbacda5ef755fb58c79482e1ea2#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R26), something about the mutation of old datasets to produce new datasets, are what cause the `metasets` to be dropped on the Chart.js side? It seems like Chart.js 3.6.0 does [use referential equality on datasets](https://github.com/chartjs/Chart.js/commit/10ffe753d936c7ba059f2b436afed374bb33d252#) to perform some kind of optimization on their end. 

Thanks for this amazing package, hoping this can be a helpful pointer to the bug!

**Comment by chrmcg** [comment] 2021-11-04 00:17
FWIW, I was able to mitigate completely by fixing Chart.js at 3.5.0
```yarn add chart.js@3.5.0 react-chartjs-2@3.3.0```

**Comment by silicakes** [comment] 2021-11-04 21:18
> `yarn add chart.js@3.5.0 react-chartjs-2@3.3.0`

Still happens to me with the above.
`redraw={true}` does the trick though.

**Comment by dangreen** [comment] 2021-11-04 21:26
@honzahruby @chrmcg @silicakes Hi everybody

1) See https://github.com/reactchartjs/react-chartjs-2/issues/814#issuecomment-956065138
2) Please provide issue reproduction, you can fork [this codesandbox](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/multitype?file=/App.tsx)

**Comment by silicakes** [comment] 2021-11-04 21:43
> @honzahruby @chrmcg @silicakes Hi everybody
> 
> 1. See [Issue with production build of react. #814 (comment)](https://github.com/reactchartjs/react-chartjs-2/issues/814#issuecomment-956065138)
> 2. Please provide issue reproduction, you can fork [this codesandbox](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/chart/multitype?file=/App.tsx)


Gladly!
https://codesandbox.io/s/determined-jennings-jiwkw?file=/App.tsx
Just hit whitespace or anything really. like I said - `redraw={true}` takes care of that.


output:

```
×
←→1 of 2 errors on the page
TypeError
Cannot read properties of undefined (reading 'controller')
Legend.eval
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:8366:30
Legend.generateLabels
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:8365:47
callback
https://jiwkw.csb.app/node_modules/chart.js/dist/chunks/helpers.segment.js:898:15
Legend.buildLabels
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:7961:46
Legend.update
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:7945:10
fitBoxes
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:3170:9
Object.update
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:3305:5
Chart._updateLayout
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:5943:13
Chart.update
https://jiwkw.csb.app/node_modules/chart.js/dist/chart.esm.js:5921:10
eval
https://jiwkw.csb.app/node_modules/react-chartjs-2/dist/index.modern.js:257:24
invokePassiveEffectCreate
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23487:20
HTMLUnknownElement.callCallback
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3945:14
Object.invokeGuardedCallbackDev
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3994:16
invokeGuardedCallback
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4056:31
flushPassiveEffectsImpl
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23574:9
unstable_runWithPriority
https://jiwkw.csb.app/node_modules/scheduler/cjs/scheduler.development.js:468:12
runWithPriority$1
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:11276:10
flushPassiveEffects
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23447:14
eval
https://jiwkw.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23324:11
workLoop
https://jiwkw.csb.app/node_modules/scheduler/cjs/scheduler.development.js:417:34
flushWork
https://jiwkw.csb.app/node_modules/scheduler/cjs/scheduler.development.js:390:14
MessagePort.performWorkUntilDeadline
https://jiwkw.csb.app/node_modules/scheduler/cjs/scheduler.development.js:157:27
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
```

**Comment by chrmcg** [comment] 2021-11-05 07:54
Having trouble creating a repro, but https://github.com/reactchartjs/react-chartjs-2/issues/735#issuecomment-952040550 was true for me -- some of my datasets had the same `label`, and as soon as I appended a unique ID to each, this issue stopped happening.

**Comment by dangreen** [comment] 2021-11-23 10:34
@acceh @chrmcg @silicakes Hi. Please check out [v4.0.0](https://github.com/reactchartjs/react-chartjs-2/releases/tag/v4.0.0) with the new [`datasetIdKey`](https://react-chartjs-2.netlify.app/docs/working-with-datasets) prop.

**Comment by dangreen** [comment] 2021-12-10 09:41
@acceh Is this issue still relevant for you?

**Comment by susheel824127** [comment] 2022-01-07 11:58
@dangreen Still issue. i am using version "react-chartjs-2": "^4.0.0" and chart.js ^3.7.0


TypeError: Cannot read properties of undefined (reading 'map')

**Comment by dangreen** [comment] 2022-01-10 04:50
@susheel824127 Hi. Hi. Please provide issue reproduction. You can fork [this codesandbox](https://codesandbox.io/s/github/reactchartjs/react-chartjs-2/tree/master/sandboxes/bar/vertical?file=/App.tsx) to reproduce.

**Comment by cendevweb** [comment] 2022-01-12 10:37
I had the same issue  but I didn't want to re-render my chart so I fixed it only by using useCallback hook to memoized the function that returns my data. If you have a similar case, consider memoizing things 😄

**Comment by mciszczon** [comment] 2022-01-18 21:16
I had the same problem with `"chart.js": "^3.6.2"` and `"react-chartjs-2": "^4.0.0"`, but __only__ in Jest tests. The app was working fine, but the tests would fail with this:

```

    TypeError: Cannot read property 'prototype' of undefined

      33 | import { Chart as ReactChart } from 'react-chartjs-2'
      34 |
    > 35 | ChartJS.register(
         |         ^
      36 |   ArcElement,
      37 |   LineElement,
      38 |   BarElement,

      at TypedRegistry.isForType (node_modules/chart.js/dist/chart.js:6005:74)
      at Registry._getRegistryForType (node_modules/chart.js/dist/chart.js:6148:15)
      at node_modules/chart.js/dist/chart.js:6128:41
          at Array.forEach (<anonymous>)
      at Registry._each (node_modules/chart.js/dist/chart.js:6127:15)
      at Registry.add (node_modules/chart.js/dist/chart.js:6085:10)
      at Function.register (node_modules/chart.js/dist/chart.js:7407:16)
      ...
```

I found out that the issue is fixed if I move the `ChartJS.register()` call to be in the body component, and not outside of it, i.e.

```js
const Component = () => {
	ChartJS.register()
	...
}
```

instead of

```js
ChartJS.register()

const Component = () => {
	...
}

**Comment by dangreen** [comment] 2022-01-19 07:17
I'm closing the issue, due to nobody gave reproduction.

@mciszczon Hi. This issue in Chart.js, not in react-chartjs-2.

@susheel824127 @cendevweb If you still have issues, please create new one with provided reproduction.

**Closed by dangreen** 2022-01-19 07:17 UTC

**Comment by mciszczon** [comment] 2022-01-19 13:24
> @mciszczon Hi. This issue in Chart.js, not in react-chartjs-2.

Sure, just wanted to post a solution which worked for me and was similar to issues experiences by people in the thread :)

**Comment by ChazUK** [comment] 2022-07-04 13:40
@mciszczon Thank you for posting that, I was also coming up with that error.

**Comment by fawwad123** [comment] 2023-02-06 18:07
I am facing issue using chartjs using typescript

"chart.js": "^4.0.0",
"react-chartjs-2": "^5.0.0",


Uncaught TypeError: Cannot use 'in' operator to search for 'id' in null
    at isIChartComponent (core.typedRegistry.js:116:1)
    at TypedRegistry.register (core.typedRegistry.js:28:1)
    at Registry._exec (core.registry.js:154:1)
    at core.registry.js:142:1
    at each (helpers.core.ts:149:1)
    at core.registry.js:134:1
    at Array.forEach (<anonymous>)
    at Registry._each (core.registry.js:125:1)
    at Registry.add (core.registry.js:26:1)
    at Chart.register (core.controller.js:126:1)


import { FC } from "react"
import {Bar} from 'react-chartjs-2'
import {
      Chart as ChartJS,
      CategoryScale,
      LinearScale,
      BarElement,
      Title,
      Tooltip,
      Legend,
      PointElement,
      LineElement,
} from 'chart.js';



interface BarProps {
    chartData: any
}

const options = {
    plugins: {
      legend: {
        display: false,
      },
    },
  };

const BarChart : FC<BarProps>= ({chartData}) => {
  ChartJS.register(
    CategoryScale,
    LinearScale,
    BarElement,
    Title,
    Tooltip,
    Legend,
    PointElement,
    LineElement,
  );
    return <Bar data={chartData} options={options}/>
  }
  
  export default BarChart`

**Comment by kritika966** [comment] 2023-04-25 09:07
I am facing the kind of same issue that is cannot read the properties of undefined _custom in chart.js when i click on bar in bar graph. Using react-chartjs-2 . Can you please help me with this?
