### ISSUE TITLE
import react-chartjs-2 causes a run time error!

### ISSUE THREAD

**Issue by afshinmoshrefi** [reactchartjs/react-chartjs-2#635] opened 2021-04-06 02:14 UTC
Just started working with React and React version of ChartJS.  Got a runtime error as soon as I added the import statement:
`import { Bar } from 'react-chartjs-2'; `

- I created a new app using create-react-app
- I installed react-chartjs-2 per installation instructions
- created a new component BarChart and added the above import statement. 
- BarChart component is added to App
- following runtime error is returned:

I am not sure what this error means?

------------------------------------------------------------
TypeError: Cannot read property 'defaults' of undefined
(anonymous function)
C:/Users/afshin/react_apps/chartjs/node_modules/react-chartjs-2/es/index.js:643
  640 | }(_react["default"].Component);
  641 | 
  642 | exports.Scatter = Scatter;
> 643 | var defaults = _chart["default"].defaults;
  644 | exports.defaults = defaults;

**Comment by lobaak** [comment] 2021-04-06 03:22
Looks like a duplicate of #634

**Comment by afshinmoshrefi** [comment] 2021-04-06 11:23
Thanks that was helpful.  I downgraded chart.js to 2.9.3 and got it to work:
npm install chart.js@2.9.3

**Comment by vikingbr** [comment] 2021-04-06 13:32
@afshinmoshrefi  I was looking for that now. Thanks. Work.

**Comment by YakovlevCoded** [comment] 2021-04-21 15:56
Hi! We have updated the wrapper. Try to use the latest version ^3.0.2 with Chart.js ^3.x.

**Closed by YakovlevCoded** 2021-04-21 15:56 UTC

**Comment by afshinmoshrefi** [comment] 2021-04-28 18:48
I'm trying to update my react app from library chartjs 2 to chartjs3 without any luck.
my react app is created with functions not classes.
Is there an example of a working react-chartjs-3 example that is function based?

**Comment by YakovlevCoded** [comment] 2021-04-29 08:35
@afshinmoshrefi Hi! You need to use the react-chartjs-2 library ^3.0.2 version. Don't use  react-chartjs-3. You can see examples [here](https://github.com/reactchartjs/react-chartjs-2/tree/master/example/src/charts).
